/* Generated By:JavaCC: Do not edit this line. ExpressionParseConstants.java */
package fr.imag.adele.cadse.cadseg.exp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ATTR_QUALIFIED = 1;
  /** RegularExpression Id. */
  int ATTR_LINK = 2;
  /** RegularExpression Id. */
  int ATTR_EXP = 3;
  /** RegularExpression Id. */
  int ATTR_POINT = 4;
  /** RegularExpression Id. */
  int ATTR_END = 5;
  /** RegularExpression Id. */
  int PARENT = 6;
  /** RegularExpression Id. */
  int ATTR_PARENT_ID = 7;
  /** RegularExpression Id. */
  int ATTR_PARENT_UNIQUE_NAME = 8;
  /** RegularExpression Id. */
  int ATTR_PARENT_SHORT_NAME = 9;
  /** RegularExpression Id. */
  int ATTR_PARENT_DISPLAY_NAME = 10;
  /** RegularExpression Id. */
  int ATTR_PARENT_TYPE_NAME = 11;
  /** RegularExpression Id. */
  int ATTR_ID = 12;
  /** RegularExpression Id. */
  int ATTR_QUALIFIED_NAME = 13;
  /** RegularExpression Id. */
  int ATTR_NAME = 14;
  /** RegularExpression Id. */
  int ATTR_UNIQUE_NAME = 15;
  /** RegularExpression Id. */
  int ATTR_SHORT_NAME = 16;
  /** RegularExpression Id. */
  int ATTR_DISPLAY_NAME = 17;
  /** RegularExpression Id. */
  int ATTR_TYPE_NAME = 18;
  /** RegularExpression Id. */
  int ATTR_LINK_TYPE_NAME = 19;
  /** RegularExpression Id. */
  int ATTR = 20;
  /** RegularExpression Id. */
  int OPTION_BEGIN = 21;
  /** RegularExpression Id. */
  int OPTION_KEY = 22;
  /** RegularExpression Id. */
  int OPTION_END = 23;
  /** RegularExpression Id. */
  int OPTION_SEP = 24;
  /** RegularExpression Id. */
  int ATTR_BEGIN = 25;
  /** RegularExpression Id. */
  int CST = 26;
  /** RegularExpression Id. */
  int CST_SEP = 27;

  /** Lexical state. */
  int S2 = 0;
  /** Lexical state. */
  int ATR = 1;
  /** Lexical state. */
  int OPT = 2;
  /** Lexical state. */
  int DEFAULT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"ATTR_QUALIFIED\"",
    "\"ATTR_LINK\"",
    "\"EXP\"",
    "\".\"",
    "\"}\"",
    "\"#parent\"",
    "\"#parent-id\"",
    "\"#parent-unique-name\"",
    "\"#parent-short-name\"",
    "\"#parent-display-name\"",
    "\"#parent-type-name\"",
    "\"#id\"",
    "\"#qualified-name\"",
    "\"#name\"",
    "\"#unique-name\"",
    "\"#short-name\"",
    "\"#display-name\"",
    "\"#type-name\"",
    "\"#link-type-name\"",
    "<ATTR>",
    "\"[\"",
    "<OPTION_KEY>",
    "\"]\"",
    "\"=\"",
    "\"${\"",
    "<CST>",
    "<CST_SEP>",
  };

}
