/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 * Copyright (C) 2006-2010 Adele Team/LIG/Grenoble University, France
 */
package fr.imag.adele.cadse.cadseg.exp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ATTR_QUALIFIED = 1;
  /** RegularExpression Id. */
  int ATTR_LINK = 2;
  /** RegularExpression Id. */
  int ATTR_EXP = 3;
  /** RegularExpression Id. */
  int ATTR_POINT = 4;
  /** RegularExpression Id. */
  int ATTR_END = 5;
  /** RegularExpression Id. */
  int PARENT = 6;
  /** RegularExpression Id. */
  int ATTR_PARENT_ID = 7;
  /** RegularExpression Id. */
  int ATTR_PARENT_UNIQUE_NAME = 8;
  /** RegularExpression Id. */
  int ATTR_PARENT_SHORT_NAME = 9;
  /** RegularExpression Id. */
  int ATTR_PARENT_DISPLAY_NAME = 10;
  /** RegularExpression Id. */
  int ATTR_PARENT_TYPE_NAME = 11;
  /** RegularExpression Id. */
  int ATTR_ID = 12;
  /** RegularExpression Id. */
  int ATTR_QUALIFIED_NAME = 13;
  /** RegularExpression Id. */
  int ATTR_NAME = 14;
  /** RegularExpression Id. */
  int ATTR_UNIQUE_NAME = 15;
  /** RegularExpression Id. */
  int ATTR_SHORT_NAME = 16;
  /** RegularExpression Id. */
  int ATTR_DISPLAY_NAME = 17;
  /** RegularExpression Id. */
  int ATTR_TYPE_NAME = 18;
  /** RegularExpression Id. */
  int ATTR_LINK_TYPE_NAME = 19;
  /** RegularExpression Id. */
  int ATTR = 20;
  /** RegularExpression Id. */
  int OPTION_BEGIN = 21;
  /** RegularExpression Id. */
  int OPTION_KEY = 22;
  /** RegularExpression Id. */
  int OPTION_END = 23;
  /** RegularExpression Id. */
  int OPTION_SEP = 24;
  /** RegularExpression Id. */
  int ATTR_BEGIN = 25;
  /** RegularExpression Id. */
  int CST = 26;
  /** RegularExpression Id. */
  int CST_SEP = 27;

  /** Lexical state. */
  int S2 = 0;
  /** Lexical state. */
  int ATR = 1;
  /** Lexical state. */
  int OPT = 2;
  /** Lexical state. */
  int DEFAULT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"ATTR_QUALIFIED\"",
    "\"ATTR_LINK\"",
    "\"EXP\"",
    "\".\"",
    "\"}\"",
    "\"#parent\"",
    "\"#parent-id\"",
    "\"#parent-unique-name\"",
    "\"#parent-short-name\"",
    "\"#parent-display-name\"",
    "\"#parent-type-name\"",
    "\"#id\"",
    "\"#qualified-name\"",
    "\"#name\"",
    "\"#unique-name\"",
    "\"#short-name\"",
    "\"#display-name\"",
    "\"#type-name\"",
    "\"#link-type-name\"",
    "<ATTR>",
    "\"[\"",
    "<OPTION_KEY>",
    "\"]\"",
    "\"=\"",
    "\"${\"",
    "<CST>",
    "<CST_SEP>",
  };

}
