/* Generated By:JavaCC: Do not edit this line. ExpressionParseConstants.java */
package fr.imag.adele.cadse.cadseg.exp;

public interface ExpressionParseConstants {

	int			EOF							= 0;
	int			ATTR_QUALIFIED				= 1;
	int			ATTR_LINK					= 2;
	int			ATTR_EXP					= 3;
	int			ATTR_POINT					= 4;
	int			ATTR_END					= 5;
	int			PARENT						= 6;
	int			ATTR_PARENT_ID				= 7;
	int			ATTR_PARENT_UNIQUE_NAME		= 8;
	int			ATTR_PARENT_SHORT_NAME		= 9;
	int			ATTR_PARENT_DISPLAY_NAME	= 10;
	int			ATTR_PARENT_TYPE_NAME		= 11;
	int			ATTR_ID						= 12;
	int			ATTR_QUALIFIED_NAME			= 13;
	int			ATTR_NAME					= 14;
	int			ATTR_UNIQUE_NAME			= 15;
	int			ATTR_SHORT_NAME				= 16;
	int			ATTR_DISPLAY_NAME			= 17;
	int			ATTR_TYPE_NAME				= 18;
	int			ATTR_LINK_TYPE_NAME			= 19;
	int			ATTR						= 20;
	int			OPTION_BEGIN				= 21;
	int			OPTION_KEY					= 22;
	int			OPTION_END					= 23;
	int			OPTION_SEP					= 24;
	int			ATTR_BEGIN					= 25;
	int			CST							= 26;
	int			CST_SEP						= 27;

	int			S2							= 0;
	int			ATR							= 1;
	int			OPT							= 2;
	int			DEFAULT						= 3;

	String[]	tokenImage					= { "<EOF>", "\"ATTR_QUALIFIED\"", "\"ATTR_LINK\"", "\"EXP\"", "\".\"",
			"\"}\"", "\"#parent\"", "\"#parent-id\"", "\"#parent-unique-name\"", "\"#parent-short-name\"",
			"\"#parent-display-name\"", "\"#parent-type-name\"", "\"#id\"", "\"#qualified-name\"", "\"#name\"",
			"\"#unique-name\"", "\"#short-name\"", "\"#display-name\"", "\"#type-name\"", "\"#link-type-name\"",
			"<ATTR>", "\"[\"", "<OPTION_KEY>", "\"]\"", "\"=\"", "\"${\"", "<CST>", "<CST_SEP>", };

}
